version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  test_workflow:
    jobs:
      - test

