version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18-browsers  # <- includes Chrome/Chromium & Puppeteer deps

    steps:
      - checkout

      # Install npm dependencies
      - run: npm install

      # Run tests
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build

